"""Protocol definition for Text-to-Speech engines."""
from typing import Protocol

class TTSEngine(Protocol):
    def speak(self, text: str) -> None: ...
    def generate_to_file(self, text: str, file_path: str) -> None: ...
    def list_models(self) -> list[str]: ...
    def get_active_model(self) -> str: ...
    def set_model(self, model_name: str) -> bool: ...
    def list_voices(self) -> list[str]: ...
    def get_active_voice(self) -> str: ...
    def set_voice(self, voice_id: str) -> None: ...
    def is_available(self) -> bool: ...
    def set_speed(self, speed: float) -> None: ...
    def cancel(self) -> None: ...
